// GENERATED FILE — do not edit by hand.
// Generated by tools/contracts/generate-wire-types.mjs from the contracts
// schemas; regenerate with `npm run contracts:wire`, verify freshness with
// `npm run contracts:wire:check` (G20.19, issue #490; specification §V4).
// Sources: contracts/schemas/{localized-text,catalog,route,stop}.schema.json.
// The locale allowlist owner is localized-text.schema.json — every locale
// list below is derived from it, never re-declared.
// Not projected here on purpose: the legacy-v0 / unknown-major envelope
// policies and the looser device projections (services/catalog/envelope.ts);
// identifier/pattern/limit rules and the stop allOf conditionals
// (extended→story_extended_id, base→story_base_id) stay runtime-validated by
// contracts/reader.mjs — this projection does not replace that validation.

// Locale allowlist owner: localized-text.schema.json propertyNames.enum.
export const SCHEMA_LOCALES = ['be', 'en', 'uk'] as const;
export type Locale = 'be' | 'en' | 'uk';

// localized-text.schema.json: a subset of the allowlist mapped to non-empty strings.
export type LocalizedText = { [K in Locale]?: string };

// Tier domain: catalog.schema.json routes[].layers items, shared with
// stop.schema.json access_tier (asserted equal by the generator).
export type Tier = 'base' | 'extended';

// catalog.schema.json routes[] — v1 wire shape, field names verbatim.
export interface CatalogRouteEntry {
  route_id: string;
  version: string;
  locales: Locale[];
  layers: Tier[];
  product_id?: string;
  sizes: { base: number; extended?: number };
}

// catalog.schema.json discovery_index — the versioned pointer to one city's
// index file; bytes/sha256 are verified before loading (reader.mjs).
export interface CatalogPointer {
  schema_version: 1;
  revision: string;
  path: string;
  bytes: number;
  sha256: string;
}

// The validated v1 envelope as consumers see it: the reader policy owns
// catalog_schema_version/generated_at (the web renders the v1 envelope only),
// so the view projection carries the schema-owned members below.
export interface CatalogView {
  routes: CatalogRouteEntry[];
  discovery_index: CatalogPointer | null;
}

// stop.schema.json — one entry of route.json stops[].
export interface RouteStop {
  origin?: 'official' | 'imported';
  id: string;
  position: number;
  place_id: string;
  access_tier: Tier;
  story_base_id?: string;
  story_extended_id?: string;
  trigger_radius_m?: number;
  optional?: boolean;
  preview?: { name: LocalizedText; announce: LocalizedText };
}

// route.schema.json — the bundle's route.json.
export interface RouteDoc {
  origin?: 'official' | 'imported';
  route_id: string;
  version: string;
  city_id: string;
  access: 'free_base' | 'paid';
  product_id_route?: string;
  product_id_extension?: string;
  distance_m: number;
  duration_min: number;
  cover?: string;
  polyline?: string;
  published?: boolean;
  free_stop_count: number;
  stops: RouteStop[];
}
