// GENERATED FILE — do not edit. Regenerate with:
//   node --experimental-strip-types tools/i18n/generate-messages.mjs
//
// Source of truth: contracts/ui-messages/source.json (the be base text) and
// contracts/ui-messages/translations/<locale>.json (the reviewed translations).
// G21.25 (issue #558): the catalogues are generated projections — edit the
// source/translation data, never this file; the generator's --check mode
// fails on any hand edit.
// the voluntary private rating words (20 §7, 21 §5/§6; G16.03 #74): the End invitation, the shared form, the delivery states, the own-ratings list


export const FEEDBACK_STRINGS_DATA = {
  "be": {
    "unavailable": "Водгук недаступны",
    "invalidTarget": "Спасылка на ацэнку няпоўная",
    "formTitleGuide": "Як табе гайд?",
    "formTitlePlace": "Ці варта было сюды зайсці?",
    "targetLine": (locale: string, version: string) => `мова зместу: ${locale} · версія: ${version}`,
    "scaleHint": "1 — вельмі не спадабалася · 5 — вельмі спадабалася",
    "starLabel": (score: number) => `${score} з 5`,
    "reasonsTitle": "Прычыны (неабавязкова, да трох)",
    "disclosureTitle": "Хто бачыць ацэнку",
    "disclosureBody": "Ацэнку бачыць каманда KUDY і выкарыстоўвае яе, каб паляпшаць прапановы. Публічна яна не паказваецца.",
    "disclosureAnalytics": "Гэта не аналітыка: адпраўка водгуку не ўключае згоду на аналітыку і не залежыць ад яе.",
    "send": "Адправіць",
    "deleteButton": "Выдаліць ацэнку",
    "resolveConflict": "Праверыць на серверы",
    "stateDraft": "Чарнавік захаваны на прыладзе",
    "statePending": "Захавана на прыладзе — адправім пры сетцы",
    "stateSent": "Адпраўлена",
    "stateConflict": "Канфлікт: на серверы наведшая змена",
    "stateActionRequired": "Адпраўка спынена: патрэбна ўвага",
    "stateDeletePending": "Выдаленне чакае сеткі",
    "inviteTitle": "Як табе гайд? Можна ацаніць — гэта неабавязкова.",
    "inviteRate": "Ацаніць гайд",
    "inviteDismiss": "Не, дзякуй",
    "ratePlace": "Ацаніць месца",
    "placeVisitTitle": "Ці быў ты тут?",
    "placeVisitBody": "Ацэнка месца — самаацэнка візіту, не праверанае наведванне.",
    "placeVisitAccept": "Быў тут — ацаніць",
    "mySection": "Мае ацэнкі",
    "myEmpty": "Уласных ацэнак пакуль няма",
    "myEdit": "Змяніць",
    "guideWord": "Гід",
    "placeWord": "Месца",
    "ratingOf": (score: number) => `${score} з 5`,
    "reasonText": {
      "interesting_stories": "цікавыя гісторыі",
      "clear_delivery": "зразумелая падача",
      "too_long": "задоўга",
      "hard_to_navigate": "цяжка арыентавацца",
      "audio_problem": "праблема гуку",
      "description_mismatch": "не супала з апісаннем",
      "worth_visiting": "варта наведаць",
      "hard_to_reach": "цяжка дабрацца",
      "access_problem": "праблема доступу",
    },
    "errorText": {
      "feedback-input-invalid": "Звесткі не прынятыя: праверце выбар",
      "feedback-write-failed": "Запіс не ўдаўся: паўтарыце",
      "feedback-transport-failed": "Сетка не адказала: паўтарыце",
      "feedback-send-no-draft": "Няма чарнавіка для адпраўкі",
      "feedback-resolution-required": "Спачатку праверце стан на серверы",
    },
  },
  "en": {
    "unavailable": "Feedback is unavailable",
    "invalidTarget": "The rating link is incomplete",
    "formTitleGuide": "How was the guide?",
    "formTitlePlace": "Was it worth the visit?",
    "targetLine": (locale: string, version: string) => `content language: ${locale} · version: ${version}`,
    "scaleHint": "1 — did not like it at all · 5 — liked it a lot",
    "starLabel": (score: number) => `${score} out of 5`,
    "reasonsTitle": "Reasons (optional, up to three)",
    "disclosureTitle": "Who sees the rating",
    "disclosureBody": "The KUDY team sees your rating and uses it to improve the offerings. It is never shown publicly.",
    "disclosureAnalytics": "This is not analytics: sending feedback neither includes nor requires the analytics consent.",
    "send": "Send",
    "deleteButton": "Delete rating",
    "resolveConflict": "Check on the server",
    "stateDraft": "Draft saved on this device",
    "statePending": "Saved on this device — we'll send it when online",
    "stateSent": "Sent",
    "stateConflict": "Conflict: the server has a newer change",
    "stateActionRequired": "Sending stopped: attention needed",
    "stateDeletePending": "Deletion is waiting for the network",
    "inviteTitle": "How was the guide? You can rate it — it is optional.",
    "inviteRate": "Rate the guide",
    "inviteDismiss": "No, thanks",
    "ratePlace": "Rate this place",
    "placeVisitTitle": "Have you been here?",
    "placeVisitBody": "A place rating is a self-reported visit, not a verified one.",
    "placeVisitAccept": "I've been here — rate it",
    "mySection": "My ratings",
    "myEmpty": "No own ratings yet",
    "myEdit": "Edit",
    "guideWord": "Guide",
    "placeWord": "Place",
    "ratingOf": (score: number) => `${score} out of 5`,
    "reasonText": {
      "interesting_stories": "interesting stories",
      "clear_delivery": "clear delivery",
      "too_long": "too long",
      "hard_to_navigate": "hard to navigate",
      "audio_problem": "audio problem",
      "description_mismatch": "did not match the description",
      "worth_visiting": "worth visiting",
      "hard_to_reach": "hard to reach",
      "access_problem": "access problem",
    },
    "errorText": {
      "feedback-input-invalid": "The details were not accepted: check your choice",
      "feedback-write-failed": "The write failed: try again",
      "feedback-transport-failed": "The network did not answer: try again",
      "feedback-send-no-draft": "No draft to send",
      "feedback-resolution-required": "Check the server state first",
    },
  },
  "uk": {
    "unavailable": "Відгук недоступний",
    "invalidTarget": "Посилання на оцінку неповне",
    "formTitleGuide": "Як тобі гід?",
    "formTitlePlace": "Чи варто було сюди зайти?",
    "targetLine": (locale: string, version: string) => `мова контенту: ${locale} · версія: ${version}`,
    "scaleHint": "1 — зовсім не сподобалося · 5 — дуже сподобалося",
    "starLabel": (score: number) => `${score} з 5`,
    "reasonsTitle": "Причини (необов'язково, до трьох)",
    "disclosureTitle": "Хто бачить оцінку",
    "disclosureBody": "Оцінку бачить команда KUDY і використовує її, щоб покращувати пропозиції. Публічно вона не показується.",
    "disclosureAnalytics": "Це не аналітика: надсилання відгуку не включає згоду на аналітику і не залежить від неї.",
    "send": "Надіслати",
    "deleteButton": "Видалити оцінку",
    "resolveConflict": "Перевірити на сервері",
    "stateDraft": "Чернетку збережено на пристрої",
    "statePending": "Збережено на пристрої — надішлемо, коли буде мережа",
    "stateSent": "Надіслано",
    "stateConflict": "Конфлікт: на сервері новіша зміна",
    "stateActionRequired": "Надсилання зупинено: потрібна увага",
    "stateDeletePending": "Видалення чекає мережі",
    "inviteTitle": "Як тобі гід? Можеш оцінити — це необов'язково.",
    "inviteRate": "Оцінити гід",
    "inviteDismiss": "Ні, дякую",
    "ratePlace": "Оцінити місце",
    "placeVisitTitle": "Чи був ти тут?",
    "placeVisitBody": "Оцінка місця — самооцінка візиту, не перевірене відвідування.",
    "placeVisitAccept": "Був тут — оцінити",
    "mySection": "Мої оцінки",
    "myEmpty": "Власних оцінок поки немає",
    "myEdit": "Змінити",
    "guideWord": "Гід",
    "placeWord": "Місце",
    "ratingOf": (score: number) => `${score} з 5`,
    "reasonText": {
      "interesting_stories": "цікаві історії",
      "clear_delivery": "зрозуміла подача",
      "too_long": "задовго",
      "hard_to_navigate": "важко орієнтуватися",
      "audio_problem": "проблема звуку",
      "description_mismatch": "не збіглося з описом",
      "worth_visiting": "варто відвідати",
      "hard_to_reach": "важко дістатися",
      "access_problem": "проблема доступу",
    },
    "errorText": {
      "feedback-input-invalid": "Відомості не прийнято: перевірте вибір",
      "feedback-write-failed": "Запис не вдався: повторіть",
      "feedback-transport-failed": "Мережа не відповіла: повторіть",
      "feedback-send-no-draft": "Немає чернетки для надсилання",
      "feedback-resolution-required": "Спочатку перевірте стан на сервері",
    },
  },
  "de": {
    "unavailable": "Feedback nicht verfügbar",
    "invalidTarget": "Der Bewertungslink ist unvollständig",
    "formTitleGuide": "Wie gefällt dir der Guide?",
    "formTitlePlace": "Hat sich der Besuch hier gelohnt?",
    "targetLine": (locale: string, version: string) => `Inhaltssprache: ${locale} · Version: ${version}`,
    "scaleHint": "1 — hat mir gar nicht gefallen · 5 — hat mir sehr gefallen",
    "starLabel": (score: number) => `${score} von 5`,
    "reasonsTitle": "Gründe (optional, bis zu drei)",
    "disclosureTitle": "Wer die Bewertung sieht",
    "disclosureBody": "Die Bewertung sieht das KUDY-Team und nutzt sie, um das Angebot zu verbessern. Öffentlich wird sie nicht gezeigt.",
    "disclosureAnalytics": "Das ist keine Analytik: Das Senden von Feedback schließt keine Zustimmung zu Analytics ein und hängt nicht davon ab.",
    "send": "Senden",
    "deleteButton": "Bewertung löschen",
    "resolveConflict": "Auf dem Server prüfen",
    "stateDraft": "Entwurf auf dem Gerät gespeichert",
    "statePending": "Auf dem Gerät gespeichert — wir senden, sobald ein Netz da ist",
    "stateSent": "Gesendet",
    "stateConflict": "Konflikt: auf dem Server gibt es eine neuere Änderung",
    "stateActionRequired": "Senden gestoppt: Bitte prüfen",
    "stateDeletePending": "Löschen wartet auf Netz",
    "inviteTitle": "Wie gefällt dir der Guide? Du kannst ihn bewerten — ganz unverbindlich.",
    "inviteRate": "Guide bewerten",
    "inviteDismiss": "Nein, danke",
    "ratePlace": "Ort bewerten",
    "placeVisitTitle": "Warst du hier?",
    "placeVisitBody": "Die Ortsbewertung ist eine Selbsteinschätzung des Besuchs, kein geprüfter Besuch.",
    "placeVisitAccept": "War hier — bewerten",
    "mySection": "Meine Bewertungen",
    "myEmpty": "Noch keine eigenen Bewertungen",
    "myEdit": "Ändern",
    "guideWord": "Guide",
    "placeWord": "Ort",
    "ratingOf": (score: number) => `${score} von 5`,
    "reasonText": {
      "interesting_stories": "interessante Geschichten",
      "clear_delivery": "klare Vermittlung",
      "too_long": "zu lang",
      "hard_to_navigate": "schwer sich zurechtzufinden",
      "audio_problem": "Tonproblem",
      "description_mismatch": "entsprach nicht der Beschreibung",
      "worth_visiting": "der Besuch lohnt sich",
      "hard_to_reach": "schwer zu erreichen",
      "access_problem": "Probleme mit dem Zugang",
    },
    "errorText": {
      "feedback-input-invalid": "Angaben nicht angenommen: prüfe die Auswahl",
      "feedback-write-failed": "Speichern fehlgeschlagen: erneut versuchen",
      "feedback-transport-failed": "Netz hat nicht geantwortet: erneut versuchen",
      "feedback-send-no-draft": "Kein Entwurf zum Senden",
      "feedback-resolution-required": "Zuerst den Zustand auf dem Server prüfen",
    },
  },
  "fr": {
    "unavailable": "Avis indisponible",
    "invalidTarget": "Le lien d'évaluation est incomplet",
    "formTitleGuide": "Comment trouves-tu le guide ?",
    "formTitlePlace": "Cela valait-il la peine de venir ici ?",
    "targetLine": (locale: string, version: string) => `langue du contenu : ${locale} · version : ${version}`,
    "scaleHint": "1 — je n'ai pas du tout aimé · 5 — j'ai beaucoup aimé",
    "starLabel": (score: number) => `${score} sur 5`,
    "reasonsTitle": "Raisons (facultatif, jusqu'à trois)",
    "disclosureTitle": "Qui voit l'évaluation",
    "disclosureBody": "L'équipe KUDY voit l'évaluation et l'utilise pour améliorer l'offre. Elle n'est pas montrée publiquement.",
    "disclosureAnalytics": "Ce n'est pas de l'analytique : l'envoi d'un avis n'inclut pas l'accord pour l'analytique et n'en dépend pas.",
    "send": "Envoyer",
    "deleteButton": "Supprimer l'évaluation",
    "resolveConflict": "Vérifier sur le serveur",
    "stateDraft": "Brouillon enregistré sur l'appareil",
    "statePending": "Enregistré sur l'appareil — nous enverrons avec le réseau",
    "stateSent": "Envoyé",
    "stateConflict": "Conflit : le serveur a un changement plus récent",
    "stateActionRequired": "Envoi arrêté : attention requise",
    "stateDeletePending": "Suppression en attente de réseau",
    "inviteTitle": "Comment trouves-tu le guide ? Tu peux l'évaluer — c'est facultatif.",
    "inviteRate": "Évaluer le guide",
    "inviteDismiss": "Non, merci",
    "ratePlace": "Évaluer le lieu",
    "placeVisitTitle": "As-tu été ici ?",
    "placeVisitBody": "L'évaluation du lieu est une autoévaluation de la visite, pas une visite vérifiée.",
    "placeVisitAccept": "J'y étais — évaluer",
    "mySection": "Mes évaluations",
    "myEmpty": "Pas encore d'évaluations personnelles",
    "myEdit": "Modifier",
    "guideWord": "Guide",
    "placeWord": "Lieu",
    "ratingOf": (score: number) => `${score} sur 5`,
    "reasonText": {
      "interesting_stories": "histoires intéressantes",
      "clear_delivery": "présentation claire",
      "too_long": "trop long",
      "hard_to_navigate": "difficile de s'orienter",
      "audio_problem": "problème de son",
      "description_mismatch": "ne correspondait pas à la description",
      "worth_visiting": "vaut la visite",
      "hard_to_reach": "difficile d'accéder",
      "access_problem": "problème d'accès",
    },
    "errorText": {
      "feedback-input-invalid": "Données non acceptées : vérifie la sélection",
      "feedback-write-failed": "Enregistrement échoué : réessaie",
      "feedback-transport-failed": "Le réseau n'a pas répondu : réessaie",
      "feedback-send-no-draft": "Pas de brouillon à envoyer",
      "feedback-resolution-required": "Vérifie d'abord l'état sur le serveur",
    },
  },
};
