// GENERATED FILE — do not edit. Regenerate with:
//   node --experimental-strip-types tools/i18n/generate-messages.mjs
//
// Source of truth: contracts/ui-messages/source.json (the be base text) and
// contracts/ui-messages/translations/<locale>.json (the reviewed translations).
// G21.25 (issue #558): the catalogues are generated projections — edit the
// source/translation data, never this file; the generator's --check mode
// fails on any hand edit.
// the voluntary private rating words (20 §7, 21 §5/§6; G16.03 #74): the End invitation, the shared form, the delivery states, the own-ratings list


export const FEEDBACK_STRINGS_DATA = {
  "be": {
    "unavailable": "Водгук недаступны",
    "invalidTarget": "Спасылка на ацэнку няпоўная",
    "formTitleGuide": "Як табе гайд?",
    "formTitlePlace": "Ці варта было сюды зайсці?",
    "targetLine": (locale: string, version: string) => `мова зместу: ${locale} · версія: ${version}`,
    "scaleHint": "1 — вельмі не спадабалася · 5 — вельмі спадабалася",
    "starLabel": (score: number) => `${score} з 5`,
    "reasonsTitle": "Прычыны (неабавязкова, да трох)",
    "disclosureTitle": "Хто бачыць ацэнку",
    "disclosureBody": "Ацэнку бачыць каманда KUDY і выкарыстоўвае яе, каб паляпшаць прапановы. Публічна яна не паказваецца.",
    "disclosureAnalytics": "Гэта не аналітыка: адпраўка водгуку не ўключае згоду на аналітыку і не залежыць ад яе.",
    "send": "Адправіць",
    "deleteButton": "Выдаліць ацэнку",
    "resolveConflict": "Праверыць на серверы",
    "stateDraft": "Чарнавік захаваны на прыладзе",
    "statePending": "Захавана на прыладзе — адправім пры сетцы",
    "stateSent": "Адпраўлена",
    "stateConflict": "Канфлікт: на серверы наведшая змена",
    "stateActionRequired": "Адпраўка спынена: патрэбна ўвага",
    "stateDeletePending": "Выдаленне чакае сеткі",
    "inviteTitle": "Як табе гайд? Можна ацаніць — гэта неабавязкова.",
    "inviteRate": "Ацаніць гайд",
    "inviteDismiss": "Не, дзякуй",
    "ratePlace": "Ацаніць месца",
    "placeVisitTitle": "Ці быў ты тут?",
    "placeVisitBody": "Ацэнка месца — самаацэнка візіту, не праверанае наведванне.",
    "placeVisitAccept": "Быў тут — ацаніць",
    "mySection": "Мае ацэнкі",
    "myEmpty": "Уласных ацэнак пакуль няма",
    "myEdit": "Змяніць",
    "guideWord": "Гід",
    "placeWord": "Месца",
    "ratingOf": (score: number) => `${score} з 5`,
    "reasonText": {
      "interesting_stories": "цікавыя гісторыі",
      "clear_delivery": "зразумелая падача",
      "too_long": "задоўга",
      "hard_to_navigate": "цяжка арыентавацца",
      "audio_problem": "праблема гуку",
      "description_mismatch": "не супала з апісаннем",
      "worth_visiting": "варта наведаць",
      "hard_to_reach": "цяжка дабрацца",
      "access_problem": "праблема доступу",
    },
    "errorText": {
      "feedback-input-invalid": "Звесткі не прынятыя: праверце выбар",
      "feedback-write-failed": "Запіс не ўдаўся: паўтарыце",
      "feedback-transport-failed": "Сетка не адказала: паўтарыце",
      "feedback-send-no-draft": "Няма чарнавіка для адпраўкі",
      "feedback-resolution-required": "Спачатку праверце стан на серверы",
    },
  },
  "en": {
    "unavailable": "Feedback is unavailable",
    "invalidTarget": "The rating link is incomplete",
    "formTitleGuide": "How was the guide?",
    "formTitlePlace": "Was it worth the visit?",
    "targetLine": (locale: string, version: string) => `content language: ${locale} · version: ${version}`,
    "scaleHint": "1 — did not like it at all · 5 — liked it a lot",
    "starLabel": (score: number) => `${score} out of 5`,
    "reasonsTitle": "Reasons (optional, up to three)",
    "disclosureTitle": "Who sees the rating",
    "disclosureBody": "The KUDY team sees your rating and uses it to improve the offerings. It is never shown publicly.",
    "disclosureAnalytics": "This is not analytics: sending feedback neither includes nor requires the analytics consent.",
    "send": "Send",
    "deleteButton": "Delete rating",
    "resolveConflict": "Check on the server",
    "stateDraft": "Draft saved on this device",
    "statePending": "Saved on this device — we'll send it when online",
    "stateSent": "Sent",
    "stateConflict": "Conflict: the server has a newer change",
    "stateActionRequired": "Sending stopped: attention needed",
    "stateDeletePending": "Deletion is waiting for the network",
    "inviteTitle": "How was the guide? You can rate it — it is optional.",
    "inviteRate": "Rate the guide",
    "inviteDismiss": "No, thanks",
    "ratePlace": "Rate this place",
    "placeVisitTitle": "Have you been here?",
    "placeVisitBody": "A place rating is a self-reported visit, not a verified one.",
    "placeVisitAccept": "I've been here — rate it",
    "mySection": "My ratings",
    "myEmpty": "No own ratings yet",
    "myEdit": "Edit",
    "guideWord": "Guide",
    "placeWord": "Place",
    "ratingOf": (score: number) => `${score} out of 5`,
    "reasonText": {
      "interesting_stories": "interesting stories",
      "clear_delivery": "clear delivery",
      "too_long": "too long",
      "hard_to_navigate": "hard to navigate",
      "audio_problem": "audio problem",
      "description_mismatch": "did not match the description",
      "worth_visiting": "worth visiting",
      "hard_to_reach": "hard to reach",
      "access_problem": "access problem",
    },
    "errorText": {
      "feedback-input-invalid": "The details were not accepted: check your choice",
      "feedback-write-failed": "The write failed: try again",
      "feedback-transport-failed": "The network did not answer: try again",
      "feedback-send-no-draft": "No draft to send",
      "feedback-resolution-required": "Check the server state first",
    },
  },
  "uk": {
    "unavailable": "Відгук недоступний",
    "invalidTarget": "Посилання на оцінку неповне",
    "formTitleGuide": "Як тобі гід?",
    "formTitlePlace": "Чи варто було сюди зайти?",
    "targetLine": (locale: string, version: string) => `мова контенту: ${locale} · версія: ${version}`,
    "scaleHint": "1 — зовсім не сподобалося · 5 — дуже сподобалося",
    "starLabel": (score: number) => `${score} з 5`,
    "reasonsTitle": "Причини (необов'язково, до трьох)",
    "disclosureTitle": "Хто бачить оцінку",
    "disclosureBody": "Оцінку бачить команда KUDY і використовує її, щоб покращувати пропозиції. Публічно вона не показується.",
    "disclosureAnalytics": "Це не аналітика: надсилання відгуку не включає згоду на аналітику і не залежить від неї.",
    "send": "Надіслати",
    "deleteButton": "Видалити оцінку",
    "resolveConflict": "Перевірити на сервері",
    "stateDraft": "Чернетку збережено на пристрої",
    "statePending": "Збережено на пристрої — надішлемо, коли буде мережа",
    "stateSent": "Надіслано",
    "stateConflict": "Конфлікт: на сервері новіша зміна",
    "stateActionRequired": "Надсилання зупинено: потрібна увага",
    "stateDeletePending": "Видалення чекає мережі",
    "inviteTitle": "Як тобі гід? Можеш оцінити — це необов'язково.",
    "inviteRate": "Оцінити гід",
    "inviteDismiss": "Ні, дякую",
    "ratePlace": "Оцінити місце",
    "placeVisitTitle": "Чи був ти тут?",
    "placeVisitBody": "Оцінка місця — самооцінка візиту, не перевірене відвідування.",
    "placeVisitAccept": "Був тут — оцінити",
    "mySection": "Мої оцінки",
    "myEmpty": "Власних оцінок поки немає",
    "myEdit": "Змінити",
    "guideWord": "Гід",
    "placeWord": "Місце",
    "ratingOf": (score: number) => `${score} з 5`,
    "reasonText": {
      "interesting_stories": "цікаві історії",
      "clear_delivery": "зрозуміла подача",
      "too_long": "задовго",
      "hard_to_navigate": "важко орієнтуватися",
      "audio_problem": "проблема звуку",
      "description_mismatch": "не збіглося з описом",
      "worth_visiting": "варто відвідати",
      "hard_to_reach": "важко дістатися",
      "access_problem": "проблема доступу",
    },
    "errorText": {
      "feedback-input-invalid": "Відомості не прийнято: перевірте вибір",
      "feedback-write-failed": "Запис не вдався: повторіть",
      "feedback-transport-failed": "Мережа не відповіла: повторіть",
      "feedback-send-no-draft": "Немає чернетки для надсилання",
      "feedback-resolution-required": "Спочатку перевірте стан на сервері",
    },
  },
};
