// GENERATED FILE — do not edit. Regenerate with:
//   node --experimental-strip-types tools/i18n/generate-messages.mjs
//
// Source of truth: contracts/ui-messages/source.json (the be base text) and
// contracts/ui-messages/translations/<locale>.json (the reviewed translations).
// G21.25 (issue #558): the catalogues are generated projections — edit the
// source/translation data, never this file; the generator's --check mode
// fails on any hand edit.
// the shared UI chrome words (G06.05 #280; G14.04.d #305; G06.10 #432, #403; UX 05 #351; G15.03 #70)

import { completeUiLocaleSelfNames, type CompleteUiLocaleCode } from "../contracts/ui-locales.ts";
import type { UiStrings } from "../contracts/ui-message-types.ts";

export const UI_STRINGS: Record<CompleteUiLocaleCode, UiStrings> = {
  "be": {
    "access": {
      "free": "Бясплатна",
      "mixed": "Змешана",
      "paid": "Платна",
    },
    "back": "Назад",
    "backToCity": "Горад",
    "cancel": "Скасаваць",
    "catalogTemporarilyUnavailable": "Каталог часова недаступны",
    "catalogUnavailable": "Каталог недаступны",
    "collectionUnavailable": "Падборка недаступная",
    "collectionUnresolved": "Некаторыя члены падборкі пакуль не апублікаваныя.",
    "currentWalk": "Бягучая прагулка",
    "degradedData": "Частка звестак часова недаступная",
    "differenceText": {
      "duration_unknown": "час не ацэнены",
      "over_time": "даўжэй за запыт",
      "season_not_recommended": "не для гэтага сезону",
      "season_unassessed": "сезон не ацэнены",
      "theme_mismatch": "іншая тэма",
    },
    "discoveryAlternatives": "Іншыя варыянты",
    "discoveryEmpty": "Нічога дакладна не падыходзіць — пасмякчыце выбар або паглядзіце іншыя варыянты.",
    "discoveryTemporarilyUnavailable": "Падбор зараз недаступны",
    "discoveryTitle": "Чым заняцца",
    "discoveryUnavailable": "Падбор недаступны",
    "durationLabel": "Працягласць",
    "durationMinutes": (minutes: number) => `Час: ${minutes} хв`,
    "durationRange": (minMinutes: number, maxMinutes: number) => `Час: ад ${minMinutes} да ${maxMinutes} хв`,
    "freeStopsCount": (count: number) => `Кропак бясплатна: ${count}`,
    "guidesLink": "Гіды →",
    "heardCount": (count: number) => `праслышана: ${count}`,
    "historyUnavailable": "Гісторыя недаступная.",
    "kudyLink": "KUDY →",
    "languageLabel": "Мова",
    "languageSelfNames": completeUiLocaleSelfNames(),
    "languagesLine": (textLocales: readonly string[]) => `Мовы: ${textLocales.join(", ")}`,
    "liveRowLine": (state: string, day: string, heard: number) => `${state} — з ${day} — праслышана: ${heard}`,
    "loading": "Загрузка…",
    "locked": "Зачынена",
    "myKudy": "KUDY",
    "nearby": "Побач →",
    "noCurrentWalk": "Бягучай прагулкі няма",
    "noPastWalks": "Папярэдніх праходаў няма",
    "notFoundHint": "Каталог чакае — вяртайцеся да яго кнопкай «Назад».",
    "notFoundTitle": "Такога экрана няма",
    "notPublished": "не апублікавана",
    "pastRowLine": (startedDay: string, finishedDay: string | null, heard: number) => `${startedDay} — ${finishedDay ?? "—"} — праслышана: ${heard}`,
    "pastWalks": "Папярэднія праходы",
    "previewUnavailable": "Прэв'ю часова недаступны",
    "reasonText": {
      "editorial": "рэдакцыйны выбар",
      "season_recommended": "рэкамендавана на гэты сезон",
      "theme_match": "тэма",
      "within_time": "падыходзіць па часе",
    },
    "retry": "Паўтарыць",
    "seasonName": {
      "autumn": "Восень",
      "spring": "Вясна",
      "summer": "Лета",
      "winter": "Зіма",
    },
    "sizeMb": (mb: number) => `Памер: ${mb} МБ`,
    "stateLabel": {
      "active": "актыўная",
      "finished": "завершаная",
      "paused": "прыпыненая",
    },
    "stopNumber": (position: number) => `Кропка ${position}`,
    "stopsCount": (count: number) => `Кропкі: ${count}`,
    "stopsLabel": "Кропкі",
    "switchAccept": "Завершыць і пачаць",
    "switchConfirm": (liveTitle: string, candidateTitle: string) => `Завяршыць «${liveTitle}» і пачаць «${candidateTitle}»?`,
    "textAudioLine": (textLocales: readonly string[], audioLocales: readonly string[]) => `Тэкст: ${textLocales.join(", ")}${audioLocales.length > 0 ? `; аўдыё: ${audioLocales.join(", ")}` : ""}`,
    "timeCap": (minutes: number) => minutes === 60 ? `Да гадзіны` : minutes === 120 ? `Да дзвюх гадзін` : minutes === 240 ? `На паўдня` : `Да ${minutes} хв`,
    "timeUnlimited": "Без абмежавання",
    "validCache": "Папярэдні валідны кэш",
    "walk": "Прагулка",
    "whatToDo": "Чым заняцца →",
  },
  "en": {
    "access": {
      "free": "Free",
      "mixed": "Mixed",
      "paid": "Paid",
    },
    "back": "Back",
    "backToCity": "City",
    "cancel": "Cancel",
    "catalogTemporarilyUnavailable": "Catalog temporarily unavailable",
    "catalogUnavailable": "Catalog unavailable",
    "collectionUnavailable": "Collection unavailable",
    "collectionUnresolved": "Some collection members are not published yet.",
    "currentWalk": "Current walk",
    "degradedData": "Some data temporarily unavailable",
    "differenceText": {
      "duration_unknown": "duration not assessed",
      "over_time": "longer than asked",
      "season_not_recommended": "not for this season",
      "season_unassessed": "season not assessed",
      "theme_mismatch": "different theme",
    },
    "discoveryAlternatives": "Other options",
    "discoveryEmpty": "Nothing matches exactly — relax the choice or look at the other options.",
    "discoveryTemporarilyUnavailable": "Discovery is temporarily unavailable",
    "discoveryTitle": "What to do",
    "discoveryUnavailable": "Discovery unavailable",
    "durationLabel": "Duration",
    "durationMinutes": (minutes: number) => `Time: ${minutes} min`,
    "durationRange": (minMinutes: number, maxMinutes: number) => `Time: ${minMinutes}–${maxMinutes} min`,
    "freeStopsCount": (count: number) => `Free stops: ${count}`,
    "guidesLink": "Guides →",
    "heardCount": (count: number) => `heard: ${count}`,
    "historyUnavailable": "History unavailable.",
    "kudyLink": "KUDY →",
    "languageLabel": "Language",
    "languageSelfNames": completeUiLocaleSelfNames(),
    "languagesLine": (textLocales: readonly string[]) => `Languages: ${textLocales.join(", ")}`,
    "liveRowLine": (state: string, day: string, heard: number) => `${state} — from ${day} — heard: ${heard}`,
    "loading": "Loading…",
    "locked": "Locked",
    "myKudy": "KUDY",
    "nearby": "Nearby →",
    "noCurrentWalk": "No current walk",
    "noPastWalks": "No previous walks",
    "notFoundHint": "The catalog is waiting — use «Back» to return to it.",
    "notFoundTitle": "No such screen",
    "notPublished": "not published",
    "pastRowLine": (startedDay: string, finishedDay: string | null, heard: number) => `${startedDay} — ${finishedDay ?? "—"} — heard: ${heard}`,
    "pastWalks": "Previous walks",
    "previewUnavailable": "Preview temporarily unavailable",
    "reasonText": {
      "editorial": "editorial pick",
      "season_recommended": "recommended for the season",
      "theme_match": "theme",
      "within_time": "fits the time",
    },
    "retry": "Retry",
    "seasonName": {
      "autumn": "Autumn",
      "spring": "Spring",
      "summer": "Summer",
      "winter": "Winter",
    },
    "sizeMb": (mb: number) => `Size: ${mb} MB`,
    "stateLabel": {
      "active": "active",
      "finished": "finished",
      "paused": "paused",
    },
    "stopNumber": (position: number) => `Stop ${position}`,
    "stopsCount": (count: number) => `Stops: ${count}`,
    "stopsLabel": "Stops",
    "switchAccept": "Finish and start",
    "switchConfirm": (liveTitle: string, candidateTitle: string) => `Finish “${liveTitle}” and start “${candidateTitle}”?`,
    "textAudioLine": (textLocales: readonly string[], audioLocales: readonly string[]) => `Text: ${textLocales.join(", ")}${audioLocales.length > 0 ? `; audio: ${audioLocales.join(", ")}` : ""}`,
    "timeCap": (minutes: number) => minutes === 60 ? `Up to an hour` : minutes === 120 ? `Up to two hours` : minutes === 240 ? `Half a day` : `Up to ${minutes} min`,
    "timeUnlimited": "No limit",
    "validCache": "Previous valid cache",
    "walk": "Walk",
    "whatToDo": "What to do →",
  },
  "uk": {
    "access": {
      "free": "Безкоштовно",
      "mixed": "Змішано",
      "paid": "Платно",
    },
    "back": "Назад",
    "backToCity": "Місто",
    "cancel": "Скасувати",
    "catalogTemporarilyUnavailable": "Каталог тимчасово недоступний",
    "catalogUnavailable": "Каталог недоступний",
    "collectionUnavailable": "Підбірка недоступна",
    "collectionUnresolved": "Деякі члени підбірки ще не опубліковані.",
    "currentWalk": "Поточна прогулянка",
    "degradedData": "Частина даних тимчасово недоступна",
    "differenceText": {
      "duration_unknown": "час не оцінено",
      "over_time": "довше за запит",
      "season_not_recommended": "не для цього сезону",
      "season_unassessed": "сезон не оцінено",
      "theme_mismatch": "інша тема",
    },
    "discoveryAlternatives": "Інші варіанти",
    "discoveryEmpty": "Нічого точно не підходить — послабте вибір або подивіться інші варіанти.",
    "discoveryTemporarilyUnavailable": "Підбір зараз недоступний",
    "discoveryTitle": "Чим зайнятися",
    "discoveryUnavailable": "Підбір недоступний",
    "durationLabel": "Тривалість",
    "durationMinutes": (minutes: number) => `Час: ${minutes} хв`,
    "durationRange": (minMinutes: number, maxMinutes: number) => `Час: від ${minMinutes} до ${maxMinutes} хв`,
    "freeStopsCount": (count: number) => `Точок безкоштовно: ${count}`,
    "guidesLink": "Гіди →",
    "heardCount": (count: number) => `прослухано: ${count}`,
    "historyUnavailable": "Історія недоступна.",
    "kudyLink": "KUDY →",
    "languageLabel": "Мова",
    "languageSelfNames": completeUiLocaleSelfNames(),
    "languagesLine": (textLocales: readonly string[]) => `Мови: ${textLocales.join(", ")}`,
    "liveRowLine": (state: string, day: string, heard: number) => `${state} — з ${day} — прослухано: ${heard}`,
    "loading": "Завантаження…",
    "locked": "Зачинено",
    "myKudy": "KUDY",
    "nearby": "Поруч →",
    "noCurrentWalk": "Поточної прогулянки немає",
    "noPastWalks": "Попередніх прогулянок немає",
    "notFoundHint": "Каталог чекає — повертайтеся до нього кнопкою «Назад».",
    "notFoundTitle": "Такого екрана немає",
    "notPublished": "не опубліковано",
    "pastRowLine": (startedDay: string, finishedDay: string | null, heard: number) => `${startedDay} — ${finishedDay ?? "—"} — прослухано: ${heard}`,
    "pastWalks": "Попередні прогулянки",
    "previewUnavailable": "Прев'ю тимчасово недоступне",
    "reasonText": {
      "editorial": "редакційний вибір",
      "season_recommended": "рекомендовано на цей сезон",
      "theme_match": "тема",
      "within_time": "підходить за часом",
    },
    "retry": "Повторити",
    "seasonName": {
      "autumn": "Осінь",
      "spring": "Весна",
      "summer": "Літо",
      "winter": "Зима",
    },
    "sizeMb": (mb: number) => `Розмір: ${mb} МБ`,
    "stateLabel": {
      "active": "активна",
      "finished": "завершена",
      "paused": "призупинена",
    },
    "stopNumber": (position: number) => `Точка ${position}`,
    "stopsCount": (count: number) => `Точки: ${count}`,
    "stopsLabel": "Точки",
    "switchAccept": "Завершити й почати",
    "switchConfirm": (liveTitle: string, candidateTitle: string) => `Завершити «${liveTitle}» і почати «${candidateTitle}»?`,
    "textAudioLine": (textLocales: readonly string[], audioLocales: readonly string[]) => `Текст: ${textLocales.join(", ")}${audioLocales.length > 0 ? `; аудіо: ${audioLocales.join(", ")}` : ""}`,
    "timeCap": (minutes: number) => minutes === 60 ? `До години` : minutes === 120 ? `До двох годин` : minutes === 240 ? `На пів дня` : `До ${minutes} хв`,
    "timeUnlimited": "Без обмеження",
    "validCache": "Попередній валідний кеш",
    "walk": "Прогулянка",
    "whatToDo": "Чим зайнятися →",
  },
};
